language: node_js
cache:
  directories:
    -~/.npm
node_js: 
  -'12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $gitHub_token
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "deploy release"
  on:
    branch: master